### ISSUE TITLE
AviTab/ChartFox 

### ISSUE THREAD

**Issue by Luberss** [fpw/avitab#120]
it is possible to display Charts on the tablet directly from ChartFox?  it shows me a message like in the attached photo!
![IMG_20220713_192310217](https://user-images.githubusercontent.com/43652178/180027596-df5dc67d-d644-44cd-bff2-aeac85ee35be.jpg)

**Comment by jonaseberle** [comment]
Can you reproduce the error with that chart at https://chartfox.org/EPMO?

**Comment by fpw** [comment]
That seems to be an error in the Chartfox data. Their API returns the URL for that chart as `https://www.ais.pansa.pl/aip/pliki/    EP_     AD_2_   EPMO   _1-1-1   _en.pdf`. The URL works without the spaces, but I can't simply strip the spaces because other charts do have spaces.

Could you report this to Chartfox?

**Comment by Luberss** [comment]
Thanks for the answer, I'll report the problem to ChartFox
