### ISSUE TITLE
question: integrate native android apps via emulator in avitab

### ISSUE THREAD

**Issue by anthraxn8b** [fpw/avitab#189]
Is there a chance to get some kind of "generic support" for an android tablet in avitab?

The idea is to use the same apps you can use in real live also in the sim - like ENROUTE (https://github.com/Akaflieg-Freiburg/enroute).

Sth. like running an emulator on the computer which's UI is then shown on the avitab...

**Comment by fpw** [comment]
It would be possible to use an Android emulator and integrate the display into X-Plane. The device's GPS could be connected to X-Plane's datarefs etc. so that the emulated device would behave as if it were on the aircraft. 

But that would be an entirely different approach and I would see it as an alternative to AviTab and not a feature for it, so unfortunately it won't happen as part of this project.
