### ISSUE TITLE
ATIS Frequency still a bit off

### ISSUE THREAD

**Issue by pbauerochse** [fpw/avitab#30]
Hi @fpw ,

first of all thanks for this wonderful plugin. I'm really enjoying using it in the Zibo Mod.
I was happy to see, that you fixed the ATIS frequency display in 0.3.14. unfortunately there still might be some minor issues. Maybe it's an rounding error. My base airport EDDV seems to be right now, but I just recently noticed that NaviTab shows the ATIS frequency for Prag (LKPR) as 122.16 but in the simulator it actually is 122.15

Cheers and keep up the great work

Patrick

**Comment by fpw** [comment]
Hi Patrick,

AviTab takes the data from this file: `X-Plane 11\Resources\default scenery\default apt dat\Earth nav data\apt.dat`

In the current data set, the entry for LKPR is (on line 4321454 in X-Plane 11.31):
`50 12216 ATIS`

The [specification of that file format](http://developer.x-plane.com/wp-content/uploads/2015/11/XP-APT1000-Spec.pdf) states that this entry is "Frequency in MHz x 100 as Five digit integer, rounded DOWN where necessary (eg. use “12322” for 123.225MHz)".

I have no idea why X-Plane uses 122.15 and will ask on the forum.

**Comment by fpw** [comment]
This seems to be a bug in the scenery data rather than AviTab: https://gateway.x-plane.com/scenery/page/LKPR

122.16 is not a valid frequency in 25 kHz channel spacing, there are only 122.15 and then 122.175. As described in the link above, someone recently fixed this and you should get the new data on the next X-Plane update.
