### ISSUE TITLE
Embed navigraph charts as map option

### ISSUE THREAD

**Issue by jamlen** [fpw/avitab#41]
I have a Navigraph subscription, which is linked and I can get my charts in the AviTab... what I'd like it to be able to choose Navigraph Charts as a map option too, especially when they get the VFR charts added in there too!

One reason why this would be useful is in VR the Charts app seems to use hardware acceleration and therefore MoveVR can't display the window.

**Comment by fpw** [comment]
Hi,

that map is actually implemented since February, but Navigraph wants to change something in the authentication mechanism for this map and I'll have to wait for them to singal that they are done before I can release the feature. I'll ask about the current status.

You can actually turn off the hardware acceleration in the official client and use it in MoveVR: https://forums.x-plane.org/index.php?/forums/topic/181511-navigraph-beta/

**Comment by jamlen** [comment]
Awesome thanks for the quick reply! You can either close this or leave it as a reminder :)

BTW I'm a C#/Golang dev, and would like to contribute... is there any features/bugs that would be a good starting place as I've done minimal c programming before!

**Comment by fpw** [comment]
You could try getting AviTab to compile, that's a challenge coming from Go or C# since AviTab must include all of its dependencies as a static dependency: https://github.com/fpw/avitab/wiki/Compiling

If you get that to work and are still interested, get back to me :)
