### ISSUE TITLE
Missing information bar and Home button v0.4.6

### ISSUE THREAD

**Issue by goatie999** [fpw/avitab#94]
I've notice a difference between my installation of AviTab 0.4.6 and what I've seen on streams like those from FD2S and within the example screenshots for this repository  

When I open AviTab via the 'toggle tablet' option and goto (for example) the Maps page, I don't get the information bar above the map that would display information like FPS and provide the 'Home' button.  Its is however still possible to get back to the home screen via using the 'x' (close) icon for the different views.

What I am presented with is as per this example screenshot:
![b738_4k - 2021-05-20 09 21 02](https://user-images.githubusercontent.com/23122045/118981951-d5d74f80-b972-11eb-9c19-3be0b2087ee4.png)

After trying a full re-install of the plugin and playing with different X-Plane monitor resolutions I've not be able to resolve this topic.  Is there something in the config.json that I've lost along the way / been intentionally removed?

**Comment by fpw** [comment]
Hi,

this is basically by design: Zibo requested the removal of the status bar for the integration into his aircraft because it would interfere with the status bar of his own EFB. And since the windowed AviTab and the integrated one are rendered from the same image, it's missing in the window as well.

If you need the status bar in AviTab in Zibo's 737, you can disable the removal of the status bar by setting hide_header to false in AviTab.json in the aircraft folder.

Does that help?

**Comment by goatie999** [comment]
Helps perfectly, thanks.  Good to know that it's by design and to have the snippet of code to use should I want to have the option back.

Thank-you Folke
